version: "3.8"

services:
  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql

  # PHP
  php:
    build: docker/php
    ports:
      - 5173:5173
    volumes:
      - .:/var/www/html/

  # MySQL
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root

    # volumes:
    #   - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

  composer:
    build:
      context: docker/composer
    volumes:
      - .:/var/www/html/

  artisan:
    build:
      context: docker/php
    volumes:
      - .:/var/www/html/
    entrypoint: ["php", "/var/www/html/artisan"]
