version: "3.8"

services:
  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - laravel

  # PHP
  php:
    build: docker/php
    ports:
      - 5173:5173
    volumes:
      - .:/var/www/html/:cached
    networks:
      - laravel

  # MySQL
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
